### ISSUE TITLE
Want to know the dataset

### ISSUE THREAD

**Issue by NorahBIAN** [ronny3050/chord-prediction#1]
Hi! Thank you very much for sharing this code.
I would like to ask about the training dataset, can you cover it in the data or give any advice about how to find a proper chord dataset?

**Comment by ronny3050** [comment]
Hi,
Thank you for your interest in our work. We have a report detailing the exact preprocessing steps, datasets, and results. I believe this should be very helpful.

Please let me know if you have further questions. I'm closing this for now.
[Final_Report.pdf](https://github.com/ronny3050/chord-prediction/files/3154151/Final_Report.pdf)
